#!/bin/bash
#
# Sets keyboard layout in X. This is better than setxkbmap because if
# the keyboard is unplugged and replugged (e.g., because of a KVM
# switch or similar), the keyboard layout is preserved (or reloaded),
# whereas with setxkbmap it is not.

set -e

if [[ $(id -u) -ne 0 ]] ; then
  echo "Please run as root"
  exit 1
fi

cat > /etc/X11/xorg.conf.d/90-keyboard-layout.conf <<- EOM
Section "InputClass"
        Identifier "keyboard-all"
        MatchIsKeyboard "on"
        MatchDevicePath "/dev/input/event*"
        Driver "evdev"
        Option "XkbLayout" "pt"
        #Option "XkbVariant" ""
        Option "XkbOptions" "terminate:ctrl_alt_bksp"
EndSection
EOM

echo X must be restarted for changes to take effect
